# Generated by Django 2.1.5 on 2019-02-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=144)),
                ('inicio_reserva', models.DateField()),
                ('fim_resersa', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala_de_reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='booking.Sala_de_reuniao'),
        ),
    ]
