# Generated by Django 2.1.5 on 2019-02-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='fim_resersa',
            new_name='fim_reserva',
        ),
    ]
