# Generated by Django 2.1.5 on 2019-02-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190202_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='id',
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
