# Generated by Django 2.1.5 on 2019-02-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190205_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala_de_reuniao',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sala_de_reuniao',
            name='nome',
            field=models.CharField(max_length=32),
        ),
    ]
